name: Enforce Linear History

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Ensure no merge commits
        run: |
          git fetch origin main
          if [ -n "$(git rev-list --merges origin/main..HEAD)" ]; then
            echo "Merge commits detected. Use Rebase/Squash.";
            exit 1;
          fi
